name: Test Project
on:
  push:
    branches: [tests]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tests: ["test_add", "test_sub"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          sudo apt-get install libgtest-dev 
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

      - name: Run CMake
        run: |
          cmake -S ./src -B build
          cmake --build build -j 2

      - name: Run tests
        run: |
          .build/${{ matrix.tests }}
